[workspace]
members = [
    "cfr",
    "mccfr_external_sampling",
    "rps",
    "blotto",
    "kuhn",
    "dudo",
    "explot"
]
default-members = [
    "mccfr_external_sampling",
]

[profile.release]
debug = 1

[profile.dev]
opt-level = 3
