edition = "2021"
reorder_imports = true
use_small_heuristics = "Off"

#### nightly features follow
imports_layout = "Vertical"
imports_granularity = "Crate"

# Struct fields should never fit into a single line.
struct_lit_single_line = false
use_field_init_shorthand = true
